#ifndef __DEMOOBJECTS__
#define __DEMOOBJECTS__

#define nDEMO_AMBIENT_TEMP 25.0
#define nDEMO_MAX_TEMP 80.0
#define nDEMO_OBJECTS_TIMER_PERIOD 1000

extern float nGLOBAL_CURR_TEMP_INSIDE_TOASTER;
#endif